// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8PGuDmotxaMrpp4Fsv11_xJl5_0sFz5w',
    appId: '1:630965239135:web:1db6a724539ba27cf48aea',
    messagingSenderId: '630965239135',
    projectId: 'videofam-c0f70',
    authDomain: 'videofam-c0f70.firebaseapp.com',
    storageBucket: 'videofam-c0f70.appspot.com',
    measurementId: 'G-KSLLYQKTC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_sJyAmTsylq5-wBsPp73Z6uKtYLJ1waE',
    appId: '1:630965239135:android:3c727d3b85796c4df48aea',
    messagingSenderId: '630965239135',
    projectId: 'videofam-c0f70',
    storageBucket: 'videofam-c0f70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmN22cfwx1HtSF3F_6ky8Y6Pp75iWNc1E',
    appId: '1:630965239135:ios:79b66abc60185746f48aea',
    messagingSenderId: '630965239135',
    projectId: 'videofam-c0f70',
    storageBucket: 'videofam-c0f70.appspot.com',
    iosClientId: '630965239135-jnqap9kvb1vbdiih488toml3enl77jo2.apps.googleusercontent.com',
    iosBundleId: 'com.example.videofam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmN22cfwx1HtSF3F_6ky8Y6Pp75iWNc1E',
    appId: '1:630965239135:ios:a31532a40e500e8bf48aea',
    messagingSenderId: '630965239135',
    projectId: 'videofam-c0f70',
    storageBucket: 'videofam-c0f70.appspot.com',
    iosClientId: '630965239135-mebqjpkf96ja5vq5ksglv5ogvi97t89j.apps.googleusercontent.com',
    iosBundleId: 'com.example.videofam.RunnerTests',
  );
}
